server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  profiles:
    active: local
  jackson:
    timeZone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  datasource:
    testOnBorrow: true
    validationQuery: SELECT 1
    url: jdbc:h2:mem:spring_boot_ddd_boilerplate;
  jpa:
    show_sql: true
    format_sql: true
  h2:
    console:
      path: /h2-console
      enabled: true

management:
  health:
    db:
      enabled: true

logging:
  file: /home/workspace/spring-boot-boilerplate.log
  level:
    root: info
